# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y4YuZMWSlvsou9lw8gAPylrXilsxzLtT
"""

!pip install aiogram nest_asyncio

import os
import asyncio
from aiogram import Bot, Dispatcher, types
from aiogram.filters import Command

# Беремо токен із змінної оточення BOT_TOKEN
TOKEN = os.getenv("BOT_TOKEN")
if not TOKEN:
    raise RuntimeError("BOT_TOKEN не задан! Додай його у Variables на Railway.")

bot = Bot(token=TOKEN)
dp = Dispatcher()

# обработчик команды /start
@dp.message(Command("start"))
async def start_command(message: types.Message):
    await message.answer("Привет 👋 Я твой новый бот!")

# обработчик всех остальных сообщений
@dp.message()
async def echo(message: types.Message):
    await message.answer("Ты написал: " + message.text)

async def main():
    print("Бот запущен ✅")
    await dp.start_polling(bot)

if __name__ == "__main__":
    asyncio.run(main())